In [21]:

import numpy as np
import cv2
import os
 
# img_h, img_w = 32, 32
img_h, img_w = 64, 64   #根据自己数据集适当调整，影响不大
means=np.zeros((1,3))
stdevs=np.zeros((1,3))
 
folder_path = './food-101/images'
folder_path_list = os.listdir(folder_path)
 
len_ = len(folder_path_list)
i = 0
for item in folder_path_list:
    img_list = []
    image_folder_path = os.path.join(folder_path,item)
    for it in os.listdir(image_folder_path):
        img = cv2.imread(os.path.join(image_folder_path,it))
        # print(os.path.join(folder_path,item,it))
        img = cv2.resize(img,(img_w,img_h))
        img = img[:, :, :, np.newaxis]
        img_list.append(img)
        i += 1
        if i%1000 == 0:
            print(i,'/',len_*1000)    
 
    imgs = np.concatenate(img_list, axis=3)
    imgs = imgs.astype(np.float32) / 255.
    
    for i in range(3):
        pixels = imgs[:, :, i, :].ravel()  # 拉成一行
        means[0,i]+=(np.mean(pixels))
        stdevs[0,i]+=(np.std(pixels))
    print(means[:,[2,1,0]],stdevs[:,[2,1,0]])
    # BGR --> RGB ， CV读取的需要转换，PIL读取的不用转换

print(means[:,[2,1,0]],stdevs[:,[2,1,0]])
 
print("normMean = {}".format(means))


1000 / 101000
[[0.53260374 0.42720354 0.32899484]] [[0.27778339 0.28915721 0.29036242]]
1000 / 101000
[[1.09945744 0.86380515 0.68176594]] [[0.54362375 0.56905538 0.56994149]]
1000 / 101000
[[1.64219368 1.3123467  1.05306122]] [[0.81376809 0.85098225 0.84696135]]
1000 / 101000
[[2.19285887 1.77514353 1.44273898]] [[1.09541774 1.14307743 1.12944147]]
1000 / 101000
[[2.65408027 2.14851704 1.7123166 ]] [[1.4009704  1.42911959 1.3914572 ]]
1000 / 101000
[[3.21132177 2.61108455 2.09977937]] [[1.67788029 1.70549113 1.6656794 ]]
1000 / 101000
[[3.76549697 3.06797171 2.46001109]] [[1.95137414 1.98573804 1.94935259]]
1000 / 101000
[[4.27526194 3.50751603 2.83857656]] [[2.22770604 2.25845391 2.21824431]]
1000 / 101000
[[4.82588452 3.96783355 3.19458434]] [[2.48594156 2.52135953 2.49208394]]
1000 / 101000
[[5.37793404 4.41316521 3.53418511]] [[2.74366251 2.78195333 2.766536  ]]
1000 / 101000
[[5.95379168 4.89901406 3.91083252]] [[2.9931764  3.03471506 3.03904617]]
1000 / 101000
[[6.51627624 5.368

In [22]:
means = means[:,[2,1,0]]
stdevs = stdevs[:,[2,1,0]]

In [23]:
means/=101
stdevs/=101
print(means,stdevs)

[[0.54614421 0.44465557 0.34460956]] [[0.26745502 0.27089352 0.27548077]]
