In [8]:
import numpy as np
import cv2
import os

# img_h, img_w = 32, 32
img_h, img_w = 64, 64   #根据自己数据集适当调整，影响不大
means=np.zeros((1,3))
stdevs=np.zeros((1,3))
 
folder_path = './data/UECFOOD256'
folder_path_list = os.listdir(folder_path)
 
len_ = len(folder_path_list)
i = 0
for item in folder_path_list:
    img_list = []
    image_folder_path = os.path.join(folder_path,item)
    if os.path.isfile(image_folder_path):
        continue
    for it in os.listdir(image_folder_path):
        img = cv2.imread(os.path.join(image_folder_path,it))
        # print(os.path.join(folder_path,item,it))
        img = cv2.resize(img,(img_w,img_h))
        img = img[:, :, :, np.newaxis]
        img_list.append(img)
        i += 1
        if i%1000 == 0:
            print(i,'/',len_*1000)    
 
    imgs = np.concatenate(img_list, axis=3)
    imgs = imgs.astype(np.float32) / 255.
    
    for i in range(3):
        pixels = imgs[:, :, i, :].ravel()  # 拉成一行
        means[0,i]+=(np.mean(pixels))
        stdevs[0,i]+=(np.std(pixels))
    print(means[:,[2,1,0]],stdevs[:,[2,1,0]])
    # BGR --> RGB ， CV读取的需要转换，PIL读取的不用转换

print(means[:,[2,1,0]],stdevs[:,[2,1,0]])
 
print("normMean = {}".format(means))


[[0.65239263 0.5602209  0.40846026]] [[0.23334493 0.25011241 0.26169002]]
[[1.27662319 1.04637474 0.77208093]] [[0.47314252 0.51378733 0.53978464]]
[[1.91574246 1.57448089 1.21630335]] [[0.7014178  0.79377204 0.84049788]]
[[2.48372376 2.11517662 1.64430866]] [[0.89570108 0.9961624  1.08375677]]
[[3.0934186  2.5388034  1.91154832]] [[1.13435112 1.25226583 1.33472753]]
[[3.73919356 3.06023151 2.28978148]] [[1.3503342  1.48230635 1.59431511]]
[[4.39585966 3.54418585 2.60975182]] [[1.59652261 1.76909308 1.91018263]]
[[5.06359768 4.1399807  3.08120582]] [[1.833738   2.01921479 2.20356184]]
[[5.58590877 4.53469652 3.39951333]] [[2.08793274 2.29838718 2.48330918]]
[[6.21658355 5.08087015 3.84560296]] [[2.32333161 2.54744317 2.73201592]]
[[6.86714441 5.61244857 4.2360113 ]] [[2.52277122 2.79311223 3.03451298]]
[[7.37950712 6.06092992 4.62026897]] [[2.8077075  3.07689558 3.32011418]]
[[8.06894833 6.62450984 4.95303234]] [[3.00674281 3.29698594 3.57941015]]
[[8.72263801 7.12799504 5.29627612]] [

In [9]:
means = means[:,[2,1,0]]
stdevs = stdevs[:,[2,1,0]]

In [10]:
means/=256
stdevs/=256
print(means,stdevs)

[[0.60702168 0.49392965 0.35589468]] [[0.23429272 0.24887561 0.26953048]]
